// Code generated by ent, DO NOT EDIT.

package userfilter

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/citizenkz/core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldEQ(FieldUserID, v))
}

// FilterID applies equality check predicate on the "filter_id" field. It's identical to FilterIDEQ.
func FilterID(v int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldEQ(FieldFilterID, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldEQ(FieldValue, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldNotIn(FieldUserID, vs...))
}

// FilterIDEQ applies the EQ predicate on the "filter_id" field.
func FilterIDEQ(v int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldEQ(FieldFilterID, v))
}

// FilterIDNEQ applies the NEQ predicate on the "filter_id" field.
func FilterIDNEQ(v int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldNEQ(FieldFilterID, v))
}

// FilterIDIn applies the In predicate on the "filter_id" field.
func FilterIDIn(vs ...int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldIn(FieldFilterID, vs...))
}

// FilterIDNotIn applies the NotIn predicate on the "filter_id" field.
func FilterIDNotIn(vs ...int) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldNotIn(FieldFilterID, vs...))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.UserFilter {
	return predicate.UserFilter(sql.FieldContainsFold(FieldValue, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserFilter {
	return predicate.UserFilter(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserFilter {
	return predicate.UserFilter(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFilter applies the HasEdge predicate on the "filter" edge.
func HasFilter() predicate.UserFilter {
	return predicate.UserFilter(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FilterTable, FilterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFilterWith applies the HasEdge predicate on the "filter" edge with a given conditions (other predicates).
func HasFilterWith(preds ...predicate.Filter) predicate.UserFilter {
	return predicate.UserFilter(func(s *sql.Selector) {
		step := newFilterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserFilter) predicate.UserFilter {
	return predicate.UserFilter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserFilter) predicate.UserFilter {
	return predicate.UserFilter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserFilter) predicate.UserFilter {
	return predicate.UserFilter(sql.NotPredicates(p))
}
