// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AttemptsColumns holds the columns for the "attempts" table.
	AttemptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "otp", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
	}
	// AttemptsTable holds the schema information for the "attempts" table.
	AttemptsTable = &schema.Table{
		Name:       "attempts",
		Columns:    AttemptsColumns,
		PrimaryKey: []*schema.Column{AttemptsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "first_name", Type: field.TypeString, Size: 100},
		{Name: "last_name", Type: field.TypeString, Size: 100},
		{Name: "birth_date", Type: field.TypeTime, Nullable: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// AttemptAttemptsColumns holds the columns for the "attempt_attempts" table.
	AttemptAttemptsColumns = []*schema.Column{
		{Name: "attempt_id", Type: field.TypeUUID},
		{Name: "attempt_id", Type: field.TypeUUID},
	}
	// AttemptAttemptsTable holds the schema information for the "attempt_attempts" table.
	AttemptAttemptsTable = &schema.Table{
		Name:       "attempt_attempts",
		Columns:    AttemptAttemptsColumns,
		PrimaryKey: []*schema.Column{AttemptAttemptsColumns[0], AttemptAttemptsColumns[1], AttemptAttemptsColumns[0], AttemptAttemptsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "attempt_attempts_attempt_id",
				Columns:    []*schema.Column{AttemptAttemptsColumns[0], AttemptAttemptsColumns[1]},
				RefColumns: []*schema.Column{AttemptsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "attempt_attempts_attempt_id",
				Columns:    []*schema.Column{AttemptAttemptsColumns[0], AttemptAttemptsColumns[1]},
				RefColumns: []*schema.Column{AttemptsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AttemptsTable,
		UsersTable,
		AttemptAttemptsTable,
	}
)

func init() {
	AttemptAttemptsTable.ForeignKeys[0].RefTable = AttemptsTable
	AttemptAttemptsTable.ForeignKeys[1].RefTable = AttemptsTable
}
