// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/citizenkz/core/ent/benefit"
	"github.com/citizenkz/core/ent/benefitcategory"
	"github.com/citizenkz/core/ent/category"
	"github.com/citizenkz/core/ent/predicate"
)

// BenefitCategoryQuery is the builder for querying BenefitCategory entities.
type BenefitCategoryQuery struct {
	config
	ctx          *QueryContext
	order        []benefitcategory.OrderOption
	inters       []Interceptor
	predicates   []predicate.BenefitCategory
	withBenefit  *BenefitQuery
	withCategory *CategoryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BenefitCategoryQuery builder.
func (_q *BenefitCategoryQuery) Where(ps ...predicate.BenefitCategory) *BenefitCategoryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *BenefitCategoryQuery) Limit(limit int) *BenefitCategoryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *BenefitCategoryQuery) Offset(offset int) *BenefitCategoryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *BenefitCategoryQuery) Unique(unique bool) *BenefitCategoryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *BenefitCategoryQuery) Order(o ...benefitcategory.OrderOption) *BenefitCategoryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryBenefit chains the current query on the "benefit" edge.
func (_q *BenefitCategoryQuery) QueryBenefit() *BenefitQuery {
	query := (&BenefitClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(benefitcategory.Table, benefitcategory.FieldID, selector),
			sqlgraph.To(benefit.Table, benefit.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, benefitcategory.BenefitTable, benefitcategory.BenefitColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCategory chains the current query on the "category" edge.
func (_q *BenefitCategoryQuery) QueryCategory() *CategoryQuery {
	query := (&CategoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(benefitcategory.Table, benefitcategory.FieldID, selector),
			sqlgraph.To(category.Table, category.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, benefitcategory.CategoryTable, benefitcategory.CategoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BenefitCategory entity from the query.
// Returns a *NotFoundError when no BenefitCategory was found.
func (_q *BenefitCategoryQuery) First(ctx context.Context) (*BenefitCategory, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{benefitcategory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *BenefitCategoryQuery) FirstX(ctx context.Context) *BenefitCategory {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BenefitCategory ID from the query.
// Returns a *NotFoundError when no BenefitCategory ID was found.
func (_q *BenefitCategoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{benefitcategory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *BenefitCategoryQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BenefitCategory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BenefitCategory entity is found.
// Returns a *NotFoundError when no BenefitCategory entities are found.
func (_q *BenefitCategoryQuery) Only(ctx context.Context) (*BenefitCategory, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{benefitcategory.Label}
	default:
		return nil, &NotSingularError{benefitcategory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *BenefitCategoryQuery) OnlyX(ctx context.Context) *BenefitCategory {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BenefitCategory ID in the query.
// Returns a *NotSingularError when more than one BenefitCategory ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *BenefitCategoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{benefitcategory.Label}
	default:
		err = &NotSingularError{benefitcategory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *BenefitCategoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BenefitCategories.
func (_q *BenefitCategoryQuery) All(ctx context.Context) ([]*BenefitCategory, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BenefitCategory, *BenefitCategoryQuery]()
	return withInterceptors[[]*BenefitCategory](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *BenefitCategoryQuery) AllX(ctx context.Context) []*BenefitCategory {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BenefitCategory IDs.
func (_q *BenefitCategoryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(benefitcategory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *BenefitCategoryQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *BenefitCategoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*BenefitCategoryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *BenefitCategoryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *BenefitCategoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *BenefitCategoryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BenefitCategoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *BenefitCategoryQuery) Clone() *BenefitCategoryQuery {
	if _q == nil {
		return nil
	}
	return &BenefitCategoryQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]benefitcategory.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.BenefitCategory{}, _q.predicates...),
		withBenefit:  _q.withBenefit.Clone(),
		withCategory: _q.withCategory.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithBenefit tells the query-builder to eager-load the nodes that are connected to
// the "benefit" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BenefitCategoryQuery) WithBenefit(opts ...func(*BenefitQuery)) *BenefitCategoryQuery {
	query := (&BenefitClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBenefit = query
	return _q
}

// WithCategory tells the query-builder to eager-load the nodes that are connected to
// the "category" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BenefitCategoryQuery) WithCategory(opts ...func(*CategoryQuery)) *BenefitCategoryQuery {
	query := (&CategoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCategory = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BenefitID int `json:"benefit_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BenefitCategory.Query().
//		GroupBy(benefitcategory.FieldBenefitID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *BenefitCategoryQuery) GroupBy(field string, fields ...string) *BenefitCategoryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BenefitCategoryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = benefitcategory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BenefitID int `json:"benefit_id,omitempty"`
//	}
//
//	client.BenefitCategory.Query().
//		Select(benefitcategory.FieldBenefitID).
//		Scan(ctx, &v)
func (_q *BenefitCategoryQuery) Select(fields ...string) *BenefitCategorySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &BenefitCategorySelect{BenefitCategoryQuery: _q}
	sbuild.label = benefitcategory.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BenefitCategorySelect configured with the given aggregations.
func (_q *BenefitCategoryQuery) Aggregate(fns ...AggregateFunc) *BenefitCategorySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *BenefitCategoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !benefitcategory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *BenefitCategoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BenefitCategory, error) {
	var (
		nodes       = []*BenefitCategory{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withBenefit != nil,
			_q.withCategory != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BenefitCategory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BenefitCategory{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withBenefit; query != nil {
		if err := _q.loadBenefit(ctx, query, nodes, nil,
			func(n *BenefitCategory, e *Benefit) { n.Edges.Benefit = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCategory; query != nil {
		if err := _q.loadCategory(ctx, query, nodes, nil,
			func(n *BenefitCategory, e *Category) { n.Edges.Category = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *BenefitCategoryQuery) loadBenefit(ctx context.Context, query *BenefitQuery, nodes []*BenefitCategory, init func(*BenefitCategory), assign func(*BenefitCategory, *Benefit)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*BenefitCategory)
	for i := range nodes {
		fk := nodes[i].BenefitID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(benefit.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "benefit_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *BenefitCategoryQuery) loadCategory(ctx context.Context, query *CategoryQuery, nodes []*BenefitCategory, init func(*BenefitCategory), assign func(*BenefitCategory, *Category)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*BenefitCategory)
	for i := range nodes {
		fk := nodes[i].CategoryID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(category.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "category_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *BenefitCategoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *BenefitCategoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(benefitcategory.Table, benefitcategory.Columns, sqlgraph.NewFieldSpec(benefitcategory.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, benefitcategory.FieldID)
		for i := range fields {
			if fields[i] != benefitcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withBenefit != nil {
			_spec.Node.AddColumnOnce(benefitcategory.FieldBenefitID)
		}
		if _q.withCategory != nil {
			_spec.Node.AddColumnOnce(benefitcategory.FieldCategoryID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *BenefitCategoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(benefitcategory.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = benefitcategory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BenefitCategoryGroupBy is the group-by builder for BenefitCategory entities.
type BenefitCategoryGroupBy struct {
	selector
	build *BenefitCategoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *BenefitCategoryGroupBy) Aggregate(fns ...AggregateFunc) *BenefitCategoryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *BenefitCategoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BenefitCategoryQuery, *BenefitCategoryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *BenefitCategoryGroupBy) sqlScan(ctx context.Context, root *BenefitCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BenefitCategorySelect is the builder for selecting fields of BenefitCategory entities.
type BenefitCategorySelect struct {
	*BenefitCategoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *BenefitCategorySelect) Aggregate(fns ...AggregateFunc) *BenefitCategorySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *BenefitCategorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BenefitCategoryQuery, *BenefitCategorySelect](ctx, _s.BenefitCategoryQuery, _s, _s.inters, v)
}

func (_s *BenefitCategorySelect) sqlScan(ctx context.Context, root *BenefitCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
