// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/citizenkz/core/ent/benefitfilter"
	"github.com/citizenkz/core/ent/predicate"
)

// BenefitFilterDelete is the builder for deleting a BenefitFilter entity.
type BenefitFilterDelete struct {
	config
	hooks    []Hook
	mutation *BenefitFilterMutation
}

// Where appends a list predicates to the BenefitFilterDelete builder.
func (_d *BenefitFilterDelete) Where(ps ...predicate.BenefitFilter) *BenefitFilterDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BenefitFilterDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BenefitFilterDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BenefitFilterDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(benefitfilter.Table, sqlgraph.NewFieldSpec(benefitfilter.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BenefitFilterDeleteOne is the builder for deleting a single BenefitFilter entity.
type BenefitFilterDeleteOne struct {
	_d *BenefitFilterDelete
}

// Where appends a list predicates to the BenefitFilterDelete builder.
func (_d *BenefitFilterDeleteOne) Where(ps ...predicate.BenefitFilter) *BenefitFilterDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BenefitFilterDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{benefitfilter.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BenefitFilterDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
