// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/citizenkz/core/ent/benefit"
	"github.com/citizenkz/core/ent/benefitfilter"
	"github.com/citizenkz/core/ent/filter"
)

// BenefitFilterCreate is the builder for creating a BenefitFilter entity.
type BenefitFilterCreate struct {
	config
	mutation *BenefitFilterMutation
	hooks    []Hook
}

// SetBenefitID sets the "benefit_id" field.
func (_c *BenefitFilterCreate) SetBenefitID(v int) *BenefitFilterCreate {
	_c.mutation.SetBenefitID(v)
	return _c
}

// SetFilterID sets the "filter_id" field.
func (_c *BenefitFilterCreate) SetFilterID(v int) *BenefitFilterCreate {
	_c.mutation.SetFilterID(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *BenefitFilterCreate) SetValue(v string) *BenefitFilterCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *BenefitFilterCreate) SetNillableValue(v *string) *BenefitFilterCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetFrom sets the "from" field.
func (_c *BenefitFilterCreate) SetFrom(v string) *BenefitFilterCreate {
	_c.mutation.SetFrom(v)
	return _c
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (_c *BenefitFilterCreate) SetNillableFrom(v *string) *BenefitFilterCreate {
	if v != nil {
		_c.SetFrom(*v)
	}
	return _c
}

// SetTo sets the "to" field.
func (_c *BenefitFilterCreate) SetTo(v string) *BenefitFilterCreate {
	_c.mutation.SetTo(v)
	return _c
}

// SetNillableTo sets the "to" field if the given value is not nil.
func (_c *BenefitFilterCreate) SetNillableTo(v *string) *BenefitFilterCreate {
	if v != nil {
		_c.SetTo(*v)
	}
	return _c
}

// SetBenefit sets the "benefit" edge to the Benefit entity.
func (_c *BenefitFilterCreate) SetBenefit(v *Benefit) *BenefitFilterCreate {
	return _c.SetBenefitID(v.ID)
}

// SetFilter sets the "filter" edge to the Filter entity.
func (_c *BenefitFilterCreate) SetFilter(v *Filter) *BenefitFilterCreate {
	return _c.SetFilterID(v.ID)
}

// Mutation returns the BenefitFilterMutation object of the builder.
func (_c *BenefitFilterCreate) Mutation() *BenefitFilterMutation {
	return _c.mutation
}

// Save creates the BenefitFilter in the database.
func (_c *BenefitFilterCreate) Save(ctx context.Context) (*BenefitFilter, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BenefitFilterCreate) SaveX(ctx context.Context) *BenefitFilter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BenefitFilterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BenefitFilterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BenefitFilterCreate) check() error {
	if _, ok := _c.mutation.BenefitID(); !ok {
		return &ValidationError{Name: "benefit_id", err: errors.New(`ent: missing required field "BenefitFilter.benefit_id"`)}
	}
	if _, ok := _c.mutation.FilterID(); !ok {
		return &ValidationError{Name: "filter_id", err: errors.New(`ent: missing required field "BenefitFilter.filter_id"`)}
	}
	if len(_c.mutation.BenefitIDs()) == 0 {
		return &ValidationError{Name: "benefit", err: errors.New(`ent: missing required edge "BenefitFilter.benefit"`)}
	}
	if len(_c.mutation.FilterIDs()) == 0 {
		return &ValidationError{Name: "filter", err: errors.New(`ent: missing required edge "BenefitFilter.filter"`)}
	}
	return nil
}

func (_c *BenefitFilterCreate) sqlSave(ctx context.Context) (*BenefitFilter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BenefitFilterCreate) createSpec() (*BenefitFilter, *sqlgraph.CreateSpec) {
	var (
		_node = &BenefitFilter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(benefitfilter.Table, sqlgraph.NewFieldSpec(benefitfilter.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(benefitfilter.FieldValue, field.TypeString, value)
		_node.Value = &value
	}
	if value, ok := _c.mutation.From(); ok {
		_spec.SetField(benefitfilter.FieldFrom, field.TypeString, value)
		_node.From = &value
	}
	if value, ok := _c.mutation.To(); ok {
		_spec.SetField(benefitfilter.FieldTo, field.TypeString, value)
		_node.To = &value
	}
	if nodes := _c.mutation.BenefitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitfilter.BenefitTable,
			Columns: []string{benefitfilter.BenefitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BenefitID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FilterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitfilter.FilterTable,
			Columns: []string{benefitfilter.FilterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FilterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BenefitFilterCreateBulk is the builder for creating many BenefitFilter entities in bulk.
type BenefitFilterCreateBulk struct {
	config
	err      error
	builders []*BenefitFilterCreate
}

// Save creates the BenefitFilter entities in the database.
func (_c *BenefitFilterCreateBulk) Save(ctx context.Context) ([]*BenefitFilter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BenefitFilter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BenefitFilterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BenefitFilterCreateBulk) SaveX(ctx context.Context) []*BenefitFilter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BenefitFilterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BenefitFilterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
