// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/citizenkz/core/ent/benefit"
	"github.com/citizenkz/core/ent/benefitcategory"
	"github.com/citizenkz/core/ent/category"
	"github.com/citizenkz/core/ent/predicate"
)

// BenefitCategoryUpdate is the builder for updating BenefitCategory entities.
type BenefitCategoryUpdate struct {
	config
	hooks    []Hook
	mutation *BenefitCategoryMutation
}

// Where appends a list predicates to the BenefitCategoryUpdate builder.
func (_u *BenefitCategoryUpdate) Where(ps ...predicate.BenefitCategory) *BenefitCategoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBenefitID sets the "benefit_id" field.
func (_u *BenefitCategoryUpdate) SetBenefitID(v int) *BenefitCategoryUpdate {
	_u.mutation.SetBenefitID(v)
	return _u
}

// SetNillableBenefitID sets the "benefit_id" field if the given value is not nil.
func (_u *BenefitCategoryUpdate) SetNillableBenefitID(v *int) *BenefitCategoryUpdate {
	if v != nil {
		_u.SetBenefitID(*v)
	}
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *BenefitCategoryUpdate) SetCategoryID(v int) *BenefitCategoryUpdate {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *BenefitCategoryUpdate) SetNillableCategoryID(v *int) *BenefitCategoryUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// SetBenefit sets the "benefit" edge to the Benefit entity.
func (_u *BenefitCategoryUpdate) SetBenefit(v *Benefit) *BenefitCategoryUpdate {
	return _u.SetBenefitID(v.ID)
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *BenefitCategoryUpdate) SetCategory(v *Category) *BenefitCategoryUpdate {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the BenefitCategoryMutation object of the builder.
func (_u *BenefitCategoryUpdate) Mutation() *BenefitCategoryMutation {
	return _u.mutation
}

// ClearBenefit clears the "benefit" edge to the Benefit entity.
func (_u *BenefitCategoryUpdate) ClearBenefit() *BenefitCategoryUpdate {
	_u.mutation.ClearBenefit()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *BenefitCategoryUpdate) ClearCategory() *BenefitCategoryUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BenefitCategoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BenefitCategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BenefitCategoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BenefitCategoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BenefitCategoryUpdate) check() error {
	if _u.mutation.BenefitCleared() && len(_u.mutation.BenefitIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitCategory.benefit"`)
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitCategory.category"`)
	}
	return nil
}

func (_u *BenefitCategoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(benefitcategory.Table, benefitcategory.Columns, sqlgraph.NewFieldSpec(benefitcategory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.BenefitCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitcategory.BenefitTable,
			Columns: []string{benefitcategory.BenefitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BenefitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitcategory.BenefitTable,
			Columns: []string{benefitcategory.BenefitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitcategory.CategoryTable,
			Columns: []string{benefitcategory.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitcategory.CategoryTable,
			Columns: []string{benefitcategory.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{benefitcategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BenefitCategoryUpdateOne is the builder for updating a single BenefitCategory entity.
type BenefitCategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BenefitCategoryMutation
}

// SetBenefitID sets the "benefit_id" field.
func (_u *BenefitCategoryUpdateOne) SetBenefitID(v int) *BenefitCategoryUpdateOne {
	_u.mutation.SetBenefitID(v)
	return _u
}

// SetNillableBenefitID sets the "benefit_id" field if the given value is not nil.
func (_u *BenefitCategoryUpdateOne) SetNillableBenefitID(v *int) *BenefitCategoryUpdateOne {
	if v != nil {
		_u.SetBenefitID(*v)
	}
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *BenefitCategoryUpdateOne) SetCategoryID(v int) *BenefitCategoryUpdateOne {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *BenefitCategoryUpdateOne) SetNillableCategoryID(v *int) *BenefitCategoryUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// SetBenefit sets the "benefit" edge to the Benefit entity.
func (_u *BenefitCategoryUpdateOne) SetBenefit(v *Benefit) *BenefitCategoryUpdateOne {
	return _u.SetBenefitID(v.ID)
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *BenefitCategoryUpdateOne) SetCategory(v *Category) *BenefitCategoryUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the BenefitCategoryMutation object of the builder.
func (_u *BenefitCategoryUpdateOne) Mutation() *BenefitCategoryMutation {
	return _u.mutation
}

// ClearBenefit clears the "benefit" edge to the Benefit entity.
func (_u *BenefitCategoryUpdateOne) ClearBenefit() *BenefitCategoryUpdateOne {
	_u.mutation.ClearBenefit()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *BenefitCategoryUpdateOne) ClearCategory() *BenefitCategoryUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// Where appends a list predicates to the BenefitCategoryUpdate builder.
func (_u *BenefitCategoryUpdateOne) Where(ps ...predicate.BenefitCategory) *BenefitCategoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BenefitCategoryUpdateOne) Select(field string, fields ...string) *BenefitCategoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BenefitCategory entity.
func (_u *BenefitCategoryUpdateOne) Save(ctx context.Context) (*BenefitCategory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BenefitCategoryUpdateOne) SaveX(ctx context.Context) *BenefitCategory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BenefitCategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BenefitCategoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BenefitCategoryUpdateOne) check() error {
	if _u.mutation.BenefitCleared() && len(_u.mutation.BenefitIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitCategory.benefit"`)
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitCategory.category"`)
	}
	return nil
}

func (_u *BenefitCategoryUpdateOne) sqlSave(ctx context.Context) (_node *BenefitCategory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(benefitcategory.Table, benefitcategory.Columns, sqlgraph.NewFieldSpec(benefitcategory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BenefitCategory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, benefitcategory.FieldID)
		for _, f := range fields {
			if !benefitcategory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != benefitcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.BenefitCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitcategory.BenefitTable,
			Columns: []string{benefitcategory.BenefitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BenefitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitcategory.BenefitTable,
			Columns: []string{benefitcategory.BenefitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitcategory.CategoryTable,
			Columns: []string{benefitcategory.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitcategory.CategoryTable,
			Columns: []string{benefitcategory.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BenefitCategory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{benefitcategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
