// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/citizenkz/core/ent/child"
	"github.com/citizenkz/core/ent/childfilter"
	"github.com/citizenkz/core/ent/user"
)

// ChildCreate is the builder for creating a Child entity.
type ChildCreate struct {
	config
	mutation *ChildMutation
	hooks    []Hook
}

// SetFirstName sets the "first_name" field.
func (_c *ChildCreate) SetFirstName(v string) *ChildCreate {
	_c.mutation.SetFirstName(v)
	return _c
}

// SetLastName sets the "last_name" field.
func (_c *ChildCreate) SetLastName(v string) *ChildCreate {
	_c.mutation.SetLastName(v)
	return _c
}

// SetBirthDate sets the "birth_date" field.
func (_c *ChildCreate) SetBirthDate(v time.Time) *ChildCreate {
	_c.mutation.SetBirthDate(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChildCreate) SetUserID(v int) *ChildCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChildCreate) SetCreatedAt(v time.Time) *ChildCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChildCreate) SetNillableCreatedAt(v *time.Time) *ChildCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChildCreate) SetUser(v *User) *ChildCreate {
	return _c.SetUserID(v.ID)
}

// AddChildFilterIDs adds the "child_filters" edge to the ChildFilter entity by IDs.
func (_c *ChildCreate) AddChildFilterIDs(ids ...int) *ChildCreate {
	_c.mutation.AddChildFilterIDs(ids...)
	return _c
}

// AddChildFilters adds the "child_filters" edges to the ChildFilter entity.
func (_c *ChildCreate) AddChildFilters(v ...*ChildFilter) *ChildCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildFilterIDs(ids...)
}

// Mutation returns the ChildMutation object of the builder.
func (_c *ChildCreate) Mutation() *ChildMutation {
	return _c.mutation
}

// Save creates the Child in the database.
func (_c *ChildCreate) Save(ctx context.Context) (*Child, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChildCreate) SaveX(ctx context.Context) *Child {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChildCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChildCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChildCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := child.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChildCreate) check() error {
	if _, ok := _c.mutation.FirstName(); !ok {
		return &ValidationError{Name: "first_name", err: errors.New(`ent: missing required field "Child.first_name"`)}
	}
	if _, ok := _c.mutation.LastName(); !ok {
		return &ValidationError{Name: "last_name", err: errors.New(`ent: missing required field "Child.last_name"`)}
	}
	if _, ok := _c.mutation.BirthDate(); !ok {
		return &ValidationError{Name: "birth_date", err: errors.New(`ent: missing required field "Child.birth_date"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Child.user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Child.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Child.user"`)}
	}
	return nil
}

func (_c *ChildCreate) sqlSave(ctx context.Context) (*Child, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChildCreate) createSpec() (*Child, *sqlgraph.CreateSpec) {
	var (
		_node = &Child{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(child.Table, sqlgraph.NewFieldSpec(child.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.FirstName(); ok {
		_spec.SetField(child.FieldFirstName, field.TypeString, value)
		_node.FirstName = value
	}
	if value, ok := _c.mutation.LastName(); ok {
		_spec.SetField(child.FieldLastName, field.TypeString, value)
		_node.LastName = value
	}
	if value, ok := _c.mutation.BirthDate(); ok {
		_spec.SetField(child.FieldBirthDate, field.TypeTime, value)
		_node.BirthDate = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(child.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   child.UserTable,
			Columns: []string{child.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildFiltersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   child.ChildFiltersTable,
			Columns: []string{child.ChildFiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(childfilter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChildCreateBulk is the builder for creating many Child entities in bulk.
type ChildCreateBulk struct {
	config
	err      error
	builders []*ChildCreate
}

// Save creates the Child entities in the database.
func (_c *ChildCreateBulk) Save(ctx context.Context) ([]*Child, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Child, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChildMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChildCreateBulk) SaveX(ctx context.Context) []*Child {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChildCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChildCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
