// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/citizenkz/core/ent/child"
	"github.com/citizenkz/core/ent/childfilter"
	"github.com/citizenkz/core/ent/filter"
)

// ChildFilter is the model entity for the ChildFilter schema.
type ChildFilter struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ChildID holds the value of the "child_id" field.
	ChildID int `json:"child_id,omitempty"`
	// FilterID holds the value of the "filter_id" field.
	FilterID int `json:"filter_id,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChildFilterQuery when eager-loading is set.
	Edges        ChildFilterEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChildFilterEdges holds the relations/edges for other nodes in the graph.
type ChildFilterEdges struct {
	// Child holds the value of the child edge.
	Child *Child `json:"child,omitempty"`
	// Filter holds the value of the filter edge.
	Filter *Filter `json:"filter,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChildOrErr returns the Child value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChildFilterEdges) ChildOrErr() (*Child, error) {
	if e.Child != nil {
		return e.Child, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: child.Label}
	}
	return nil, &NotLoadedError{edge: "child"}
}

// FilterOrErr returns the Filter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChildFilterEdges) FilterOrErr() (*Filter, error) {
	if e.Filter != nil {
		return e.Filter, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: filter.Label}
	}
	return nil, &NotLoadedError{edge: "filter"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChildFilter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case childfilter.FieldID, childfilter.FieldChildID, childfilter.FieldFilterID:
			values[i] = new(sql.NullInt64)
		case childfilter.FieldValue:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChildFilter fields.
func (_m *ChildFilter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case childfilter.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case childfilter.FieldChildID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field child_id", values[i])
			} else if value.Valid {
				_m.ChildID = int(value.Int64)
			}
		case childfilter.FieldFilterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field filter_id", values[i])
			} else if value.Valid {
				_m.FilterID = int(value.Int64)
			}
		case childfilter.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the ChildFilter.
// This includes values selected through modifiers, order, etc.
func (_m *ChildFilter) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChild queries the "child" edge of the ChildFilter entity.
func (_m *ChildFilter) QueryChild() *ChildQuery {
	return NewChildFilterClient(_m.config).QueryChild(_m)
}

// QueryFilter queries the "filter" edge of the ChildFilter entity.
func (_m *ChildFilter) QueryFilter() *FilterQuery {
	return NewChildFilterClient(_m.config).QueryFilter(_m)
}

// Update returns a builder for updating this ChildFilter.
// Note that you need to call ChildFilter.Unwrap() before calling this method if this ChildFilter
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChildFilter) Update() *ChildFilterUpdateOne {
	return NewChildFilterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChildFilter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChildFilter) Unwrap() *ChildFilter {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChildFilter is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChildFilter) String() string {
	var builder strings.Builder
	builder.WriteString("ChildFilter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("child_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChildID))
	builder.WriteString(", ")
	builder.WriteString("filter_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FilterID))
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteByte(')')
	return builder.String()
}

// ChildFilters is a parsable slice of ChildFilter.
type ChildFilters []*ChildFilter
