// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/citizenkz/core/ent/filter"
	"github.com/citizenkz/core/ent/user"
	"github.com/citizenkz/core/ent/userfilter"
)

// UserFilterCreate is the builder for creating a UserFilter entity.
type UserFilterCreate struct {
	config
	mutation *UserFilterMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *UserFilterCreate) SetUserID(v int) *UserFilterCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetFilterID sets the "filter_id" field.
func (_c *UserFilterCreate) SetFilterID(v int) *UserFilterCreate {
	_c.mutation.SetFilterID(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *UserFilterCreate) SetValue(v string) *UserFilterCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserFilterCreate) SetUser(v *User) *UserFilterCreate {
	return _c.SetUserID(v.ID)
}

// SetFilter sets the "filter" edge to the Filter entity.
func (_c *UserFilterCreate) SetFilter(v *Filter) *UserFilterCreate {
	return _c.SetFilterID(v.ID)
}

// Mutation returns the UserFilterMutation object of the builder.
func (_c *UserFilterCreate) Mutation() *UserFilterMutation {
	return _c.mutation
}

// Save creates the UserFilter in the database.
func (_c *UserFilterCreate) Save(ctx context.Context) (*UserFilter, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserFilterCreate) SaveX(ctx context.Context) *UserFilter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserFilterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserFilterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserFilterCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserFilter.user_id"`)}
	}
	if _, ok := _c.mutation.FilterID(); !ok {
		return &ValidationError{Name: "filter_id", err: errors.New(`ent: missing required field "UserFilter.filter_id"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "UserFilter.value"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserFilter.user"`)}
	}
	if len(_c.mutation.FilterIDs()) == 0 {
		return &ValidationError{Name: "filter", err: errors.New(`ent: missing required edge "UserFilter.filter"`)}
	}
	return nil
}

func (_c *UserFilterCreate) sqlSave(ctx context.Context) (*UserFilter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserFilterCreate) createSpec() (*UserFilter, *sqlgraph.CreateSpec) {
	var (
		_node = &UserFilter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userfilter.Table, sqlgraph.NewFieldSpec(userfilter.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(userfilter.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfilter.UserTable,
			Columns: []string{userfilter.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FilterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfilter.FilterTable,
			Columns: []string{userfilter.FilterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FilterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserFilterCreateBulk is the builder for creating many UserFilter entities in bulk.
type UserFilterCreateBulk struct {
	config
	err      error
	builders []*UserFilterCreate
}

// Save creates the UserFilter entities in the database.
func (_c *UserFilterCreateBulk) Save(ctx context.Context) ([]*UserFilter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserFilter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserFilterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserFilterCreateBulk) SaveX(ctx context.Context) []*UserFilter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserFilterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserFilterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
