name: Deploy to Production

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run tests before deploy
        run: go test ./... -v

      - name: Deploy to Server via SSH
        env:
          SSH_ADDRESS: ${{ secrets.SSH_ADDRESS }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

          echo "✅ Deploying to $SSH_ADDRESS..."

          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SSH_ADDRESS 'cd /root/azamat/core && git pull'

          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SSH_ADDRESS 'cd /root/azamat/core && make start &'
