// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attempt is the predicate function for attempt builders.
type Attempt func(*sql.Selector)

// Filter is the predicate function for filter builders.
type Filter func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserFilter is the predicate function for userfilter builders.
type UserFilter func(*sql.Selector)
